# Generated by Django 5.2.7 on 2025-11-04 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='last_cleaning_date',
            field=models.DateField(default='2025-11-06'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='last_cleaning_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_cleaning', to='app.employee'),
        ),
    ]
