# Generated by Django 5.2.7 on 2025-11-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_accommodation_last_cleaning_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nif',
            field=models.CharField(max_length=15),
        ),
    ]
