# Generated by Django 5.2.7 on 2025-11-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_nif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='last_cleaning_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
