# Generated by Django 5.2.7 on 2025-10-30 22:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('nacionalidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(choices=[('RECEPCAO', 'Recepção'), ('GOVERNANCA', 'Governança'), ('MANUTENCAO', 'Manutenção'), ('GERENCIA', 'Gerência'), ('ADMIN', 'Administração')], max_length=20)),
                ('data_contratacao', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Acomodacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('STANDARD', 'Standard'), ('SUITE', 'Suíte'), ('MASTER', 'Master')], max_length=20)),
                ('capacidade_maxima', models.IntegerField()),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('OCUPADA', 'Ocupada'), ('MANUTENCAO', 'Em manutenção')], default='DISPONIVEL', max_length=20)),
                ('data_ultima_limpeza', models.DateField(blank=True, null=True)),
                ('funcionario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='app.acomodacao')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=15)),
                ('acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acomodacao')),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hospede')),
            ],
        ),
    ]
