# Generated by Django 5.2.7 on 2025-10-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('RECEPCAO', 'Recepção'), ('GOVERNANCA', 'Governança'), ('MANUTENCAO', 'Manutenção'), ('GERENCIA', 'Gerência'), ('ADMIN', 'Administração')], default='RECEPCAO', max_length=20, null=True),
        ),
    ]
