# Generated by Django 5.2.7 on 2025-10-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('RECEPCAO', 'Recepção'), ('GOVERNANCA', 'Governança'), ('MANUTENCAO', 'Manutenção'), ('GERENCIA', 'Gerência'), ('ADMIN', 'Administração')], default='RECEPCAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
