# Generated by Django 5.2.7 on 2025-10-30 23:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_funcionario_cargo_alter_funcionario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_contratacao',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
