# Generated by Django 5.2.7 on 2025-10-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_funcionario_data_contratacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
