# Generated by Django 5.2.7 on 2025-10-30 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('noregistro', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('data_contrato', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.CharField(choices=[('PRODUCAO', 'Producao'), ('CHEFE_PRODUCAO', 'Chefe Producao'), ('INSPECAO', 'Inspecao'), ('MANUTENCAO', 'Manutencao'), ('ADMIN', 'Admin')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=25)),
                ('descricao', models.CharField(max_length=1000)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=400)),
                ('encarregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('foto', models.ImageField(upload_to='maquinas/fotos/')),
                ('descricao', models.CharField(max_length=3000)),
                ('historico', models.ManyToManyField(blank=True, to='app.manutencao')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_final', models.DateTimeField(blank=True, null=True)),
                ('data_inspecao', models.DateField(blank=True, null=True)),
                ('status_inspecao', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], max_length=50)),
                ('qrcode', models.ImageField(upload_to='Lote/qrcode/')),
                ('encarregado_inspecao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.funcionario')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.maquina')),
                ('produtos', models.ManyToManyField(blank=True, to='app.produto')),
            ],
        ),
    ]
