# Generated by Django 5.2.7 on 2025-10-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producao'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='nome',
            field=models.CharField(default='Producao Padrao', max_length=100),
            preserve_default=False,
        ),
    ]
