# Generated by Django 5.2.7 on 2025-10-31 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_cargo_customuser_nome_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
