# Generated by Django 5.2.5 on 2025-08-20 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FavoriteMovies_movie_FK', to='app.movies')),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FavoriteMovies_user_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
