# Generated by Django 5.2.5 on 2025-09-04 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('token_creation_date', models.DateField()),
                ('insertion_date', models.DateTimeField(auto_now_add=True)),
                ('conversion_rate', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('cpf', models.CharField(max_length=12, unique=True)),
                ('rg', models.CharField(max_length=12, unique=True)),
                ('birth_date', models.DateField()),
                ('address_country', models.CharField(max_length=150)),
                ('address_state', models.CharField(max_length=150)),
                ('address_city', models.CharField(max_length=150)),
                ('address_district', models.CharField(max_length=150)),
                ('address_street', models.CharField(max_length=150)),
                ('address_zip_code', models.CharField(max_length=15)),
                ('address_number', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_user_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_loss', models.BooleanField(default=True)),
                ('input_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('output_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
                ('value3', models.IntegerField()),
                ('bet_date', models.DateTimeField(auto_now_add=True)),
                ('account_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_account_FK', to='app.account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountToken_account_FK', to='app.account')),
                ('token_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountToken_token_FK', to='app.token')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('token_source_amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('token_target_amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('account_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_account_FK', to='app.account')),
                ('token_source_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_token_source_FK', to='app.token')),
                ('token_target_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_token_target_FK', to='app.token')),
            ],
        ),
    ]
