# Generated by Django 4.2.7 on 2025-11-06 23:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('standard', 'Standard'), ('suite', 'Suíte'), ('master', 'Master')], max_length=20)),
                ('capacidade', models.PositiveIntegerField()),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupada', 'Ocupada'), ('manutencao', 'Em manutenção')], default='disponivel', max_length=20)),
                ('data_ultima_limpeza', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('cargo', models.CharField(choices=[('RECEPCAO', 'Recepção'), ('GOVERNANCA', 'Governança'), ('MANUTENCAO', 'Manutenção'), ('GERENCIA', 'Gerência'), ('ADMIN', 'Admin')], max_length=20)),
                ('data_contratacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('nacionalidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='app.accommodation')),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='app.guest')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_manutencao', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
                ('acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='app.accommodation')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes', to='app.employee')),
            ],
            options={
                'ordering': ['-data_manutencao'],
            },
        ),
        migrations.CreateModel(
            name='CleaningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_limpeza', models.DateField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True)),
                ('acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limpezas', to='app.accommodation')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limpezas', to='app.employee')),
            ],
            options={
                'ordering': ['-data_limpeza'],
            },
        ),
    ]
