# Generated by Django 5.2.7 on 2025-11-11 23:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('PRODUCAO', 'Produção'), ('LIDER_PRODUCAO', 'Líder de Produção'), ('INSPECAO', 'Inspeção'), ('MANUTENCAO', 'Manutenção'), ('ADMIN', 'Administrador')], default='PRODUCAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_contratacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
