# Generated by Django 5.2.6 on 2025-09-24 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('cpf', models.CharField(max_length=12, unique=True)),
                ('registro', models.CharField(max_length=12, unique=True)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('ambientes', models.ManyToManyField(related_name='ativos', to='app.ambiente')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('WAITING', 'Aguardando responsáveis'), ('IN PROCESS', 'Em andamento'), ('PERFORMED', 'Realizado'), ('COMPLETED', 'Concluído'), ('CANCELED', 'Cancelado')], max_length=100)),
                ('start_date_status', models.DateTimeField(blank=True, null=True)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta')], max_length=10)),
                ('ambientes', models.ManyToManyField(to='app.ambiente')),
                ('ativos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tarefas_ativos', to='app.ativo')),
                ('responsibles', models.ManyToManyField(related_name='tarefas_responsible', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('OPEN', 'Aberto'), ('WAITING', 'Aguardando responsáveis'), ('IN PROCESS', 'Em andamento'), ('PERFORMED', 'Realizado'), ('COMPLETED', 'Concluído'), ('CANCELED', 'Cancelado')], max_length=100)),
                ('novo_status', models.CharField(choices=[('OPEN', 'Aberto'), ('WAITING', 'Aguardando responsáveis'), ('IN PROCESS', 'Em andamento'), ('PERFORMED', 'Realizado'), ('COMPLETED', 'Concluído'), ('CANCELED', 'Cancelado')], max_length=100)),
                ('descricao', models.TextField()),
                ('foto', models.TextField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='app.tarefas')),
            ],
        ),
    ]
