# Generated by Django 5.2.6 on 2025-10-01 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicostatus',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='tarefas',
            name='photo',
        ),
        migrations.AddField(
            model_name='ativo',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='name',
            field=models.CharField(default='Sem nome', max_length=200),
        ),
        migrations.AddField(
            model_name='historicostatus',
            name='responsibles',
            field=models.ManyToManyField(related_name='historicos_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='suggested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='ambientes',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='user_images'),
        ),
        migrations.AlterField(
            model_name='historicostatus',
            name='alterado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_alterados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicostatus',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicostatus',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskStatus_task_FK', to='app.tarefas'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='ativos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ativo'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='responsibles',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='start_date_status',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='urgency',
            field=models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta')], default='LOW', max_length=50),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('task_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notification_task_FK', to='app.tarefas')),
                ('user_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Notification_user_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TarefaStatusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='task_images')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskStatusImage_task_FK', to='app.tarefas')),
            ],
        ),
        migrations.AddField(
            model_name='ativo',
            name='ambientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos', to='app.ambiente'),
        ),
    ]
