# Generated by Django 5.2.6 on 2025-10-01 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_historicostatus_foto_remove_tarefas_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicostatus',
            name='responsibles',
        ),
    ]
