# Generated by Django 5.2.6 on 2025-10-03 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_category_ativo_category_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefas',
            name='ambientes',
        ),
    ]
