# Generated by Django 5.2.6 on 2025-10-17 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_tarefas_ambientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambientes_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_level',
            field=models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('user', 'Usuário Comum')], default='user', max_length=20),
        ),
    ]
