# Generated by Django 5.2.6 on 2025-10-17 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_ambiente_responsible_customuser_user_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_level',
        ),
    ]
