# Generated by Django 5.2.7 on 2025-10-30 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('data_contratacao', models.DateField()),
                ('cargo', models.CharField(choices=[('MOTORISTA', 'Motorista'), ('MECÂNICO', 'Mecanico'), ('SUPERVISOR_FROTA', 'Supervisor Frota'), ('ENGENHEIRO', 'Engenheiro'), ('ADMIN', 'Admin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=100, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('CARRO', 'Carro'), ('VAN', 'Van'), ('CAMINHÃO', 'Caminhao')], max_length=20)),
                ('data_aquisicao', models.DateField()),
                ('data_ultima_manutencao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva')], max_length=20)),
                ('descricao', models.TextField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funcionario_tecnico', models.ForeignKey(limit_choices_to={'cargo': 'MECÂNICO'}, on_delete=django.db.models.deletion.CASCADE, to='app.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_id', models.CharField(max_length=100, unique=True)),
                ('data_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('data_termino', models.DateField()),
                ('hora_termino', models.TimeField()),
                ('destino', models.CharField(max_length=100)),
                ('km', models.PositiveIntegerField()),
                ('motorista', models.ForeignKey(limit_choices_to={'cargo': 'MOTORISTA'}, on_delete=django.db.models.deletion.CASCADE, to='app.funcionario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.veiculo')),
            ],
        ),
    ]
