# Generated by Django 5.2.7 on 2025-10-31 01:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acomodacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('STANDARD', 'Standard'), ('SUITE', 'Suíte'), ('MASTER', 'Master')], max_length=20)),
                ('capacidade_maxima', models.PositiveIntegerField()),
                ('avaliacao_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_ultimaLimpeza', models.DateField()),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('OCUPADA', 'Ocupada'), ('MANUTENCAO', 'Em manutenção')], default='DISPONIVEL', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_inteiro', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('data_de_registro', models.DateField(default=django.utils.timezone.now)),
                ('nacionalidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=200)),
                ('registro', models.CharField(max_length=50, unique=True)),
                ('cargo', models.CharField(choices=[('RECEPCAO', 'Recepção'), ('GOVERNANCA', 'Governança'), ('MANUTENCAO', 'Manutenção'), ('GERENCIA', 'Gerência'), ('ADMIN', 'Admin')], max_length=20)),
                ('data_contratacao', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupos de usuários.', related_name='empregado_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissões do usuário.', related_name='empregado_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Limpeza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_vez_limpo', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota', models.TextField(blank=True)),
                ('acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acomodacao')),
                ('empregado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acomodacao')),
                ('empregado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acomodacao')),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hospede')),
            ],
        ),
    ]
