# Generated by Django 5.2.7 on 2025-11-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='cargo',
            field=models.CharField(choices=[('Recepçao', 'Recepção'), ('Governaca', 'Governança'), ('Manutencao', 'Manutenção'), ('Gerencia', 'Gerência'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
