# Generated by Django 5.2.7 on 2025-11-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_empregado_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='cargo',
            field=models.CharField(choices=[('Recepçao', 'Recepção'), ('Governanca', 'Governança'), ('Manutencao', 'Manutenção'), ('Gerencia', 'Gerência'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
