# Generated by Django 5.2.7 on 2025-11-12 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_empregado_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='acomodacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.acomodacao'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='hospede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hospede'),
        ),
    ]
