# Generated by Django 5.2.6 on 2025-10-29 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dataRegistro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=14)),
                ('dataInclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('codeRegistro', models.CharField(max_length=50)),
                ('codeBarras', models.CharField(max_length=50)),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorVenda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promocao', models.BooleanField(default=False)),
                ('categoria_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Produto_categoria_FK', to='app.categoria')),
                ('marca_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Produto_marca_FK', to='app.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Escaninhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=150)),
                ('quantidade', models.CharField(max_length=150)),
                ('produto_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Escaninhos_produto_FK', to='app.produto')),
                ('setor_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Escaninhos_setor_FK', to='app.setor')),
            ],
        ),
    ]
