# Generated by Django 5.2.6 on 2025-09-17 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.TextField()),
                ('nome', models.CharField(max_length=300)),
                ('estrelas', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('quantidade_avaliacões', models.DecimalField(decimal_places=0, max_digits=6)),
                ('preço', models.DecimalField(decimal_places=2, max_digits=6)),
                ('opções_parcelamento', models.CharField(max_length=300)),
                ('categoria', models.CharField(choices=[('Escritório', 'Escritório'), ('Sala de Jantar', 'Sala de Jantar'), ('Sala de Estar', 'Sala de Estar'), ('Infantil', 'Infantil'), ('Quarto', 'Quarto'), ('Banheiro', 'Banheiro'), ('Jardim e Varanda', 'Jardim e Varanda')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=12, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_do_desconto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('método_de_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'BOLETO'), ('CARTÃO DE CRÉDITO', 'CARTÃO DE CRÉDITO')], max_length=100)),
                ('status', models.CharField(choices=[('EM PROCESSAMENTO', 'EM PROCESSAMENTO'), ('PAGAMENTO APROVADO', 'PAGAMENTO APROVADO'), ('NOTA FISCAL EMITIDA', 'NOTA FISCAL EMITIDA'), ('EM PREPARAÇÃO', 'EM PREPARAÇÃO'), ('ENVIADO', 'ENVIADO'), ('RECEBIDO', 'RECEBIDO'), ('PAGAMENTO REPROVADO', 'PAGAMENTO REPROVADO'), ('CANCELADO', 'CANCELADO'), ('SOLICITAÇÃO DE DEVOLUÇÃO', 'SOLICITAÇÃO DE DEVOLUÇÃO'), ('EM DEVOLUÇÃO', 'EM DEVOLUÇÃO'), ('DEVOLUÇÃO CANCELADA', 'DEVOLUÇÃO CANCELADA')], max_length=100)),
                ('código_de_rastreamento', models.CharField(blank=True, max_length=100, null=True)),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserPlan_user_FK', to=settings.AUTH_USER_MODEL)),
                ('produto_FK', models.ManyToManyField(related_name='pedidos', to='app.produto')),
            ],
        ),
    ]
