# Generated by Django 5.2.6 on 2025-09-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='endereço_completo',
            field=models.CharField(default='Endereço não informado', max_length=500),
        ),
    ]
