# Generated by Django 5.2.6 on 2025-09-17 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_endereço_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoDeCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cartao', models.CharField(max_length=16)),
                ('data_validade', models.CharField(max_length=5)),
                ('nome_titular', models.CharField(max_length=255)),
                ('codigo_seguranca', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='cartao_de_credito',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cartaodecredito'),
        ),
    ]
