# Generated by Django 5.2.6 on 2025-09-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cartaodecredito_pedido_cartao_de_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='método_de_pagamento',
            field=models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'BOLETO'), ('CartaoDeCredito', 'CartaoDeCredito')], max_length=100),
        ),
    ]
