# Generated by Django 5.2.6 on 2025-10-29 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('numero_registro', models.CharField(max_length=15, unique=True)),
                ('data_contrato', models.DateTimeField(auto_now_add=True)),
                ('Cargo', models.CharField(choices=[('Produção', 'Produção'), ('LIDER_PRODUÇÃO', 'Lider Produção'), ('INSPEÇÃO', 'Inspeção'), (' ENGENHARIA', 'Engenharia'), ('MANUTENÇÃO', 'Manutenção'), (' ADMIN', 'Admin')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(auto_now_add=True)),
                ('data_inspecao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=50)),
                ('funcionario_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lote_funcionario_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=500)),
                ('data_manutencao', models.DateTimeField(auto_now_add=True)),
                ('funcionario_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Maquina_funcionario_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=500)),
                ('categoria_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Produto_categoria_FK', to='app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_producao', models.DateTimeField(auto_now_add=True)),
                ('lote_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producao_lote_FK', to='app.lote')),
                ('maquina_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Producao_maquina_FK', to='app.maquina')),
                ('produto_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Producao_produto_FK', to='app.produto')),
            ],
        ),
    ]
