# Generated by Django 5.2.6 on 2025-10-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='numero_registro',
            field=models.CharField(max_length=15),
        ),
    ]
