# Generated by Django 5.2.6 on 2025-10-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_numero_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='status',
        ),
        migrations.AddField(
            model_name='producao',
            name='status',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], default='Reprovado', max_length=50),
        ),
    ]
