# Generated by Django 5.2.6 on 2025-11-11 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_lote_status_producao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='funcionario_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Prod_funcionario_FK', to=settings.AUTH_USER_MODEL),
        ),
    ]
