# Generated by Django 5.2.6 on 2025-09-24 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nif', models.CharField(max_length=15, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Environment_user_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('category_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Equipment_category_FK', to='app.category')),
                ('environment_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Equipment_environment_FK', to='app.environment')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('suggested_date', models.DateTimeField()),
                ('urgency_level', models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high'), ('EXTRA_HIGH', 'extra_high')], default='LOW', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creator_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Task_creator_FK', to=settings.AUTH_USER_MODEL)),
                ('equipments_FK', models.ManyToManyField(to='app.equipment')),
                ('responsibles_FK', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('notification_read', models.BooleanField(default=False)),
                ('user_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Notification_user_FK', to=settings.AUTH_USER_MODEL)),
                ('task_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notification_task_FK', to='app.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('WAITING_RESPONSIBLE', 'Waiting Responsible'), ('ONGOING', 'Ongoing'), ('DONE', 'Done'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=50)),
                ('status_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('task_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskStatus_task_FK', to='app.task')),
                ('user_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TaskStatus_user_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='task_images')),
                ('task_status_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskStatusImage_task_FK', to='app.taskstatus')),
            ],
        ),
    ]
