# Generated by Django 5.2.6 on 2025-10-29 00:44

import somativa_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somativa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='funcionario',
            managers=[
                ('objects', somativa_app.models.FuncionarioManager()),
            ],
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
