# Generated by Django 5.2.5 on 2025-09-03 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounttoken',
            unique_together={('account_FK', 'token_FK')},
        ),
    ]
