# Generated by Django 5.2.5 on 2025-09-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_accounttoken_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttoken',
            name='balance',
            field=models.FloatField(),
        ),
    ]
