# Generated by Django 5.2.7 on 2025-10-28 23:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato XX.XXX.XXX/XXXX-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')])),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1, unique=True, validators=[django.core.validators.RegexValidator(message='Setor deve ser uma única letra maiúscula (A-Z)', regex='^[A-Z]$')])),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo_registro', models.CharField(max_length=50, unique=True)),
                ('codigo_barras', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Código de barras deve conter apenas números (8-13 dígitos)', regex='^\\d{8,13}$')])),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('informacoes_adicionais', models.TextField(blank=True, null=True)),
                ('em_promocao', models.BooleanField(default=False)),
                ('data_promocao', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='estoque.categoria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_criados', to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='estoque.marca')),
                ('promocao_alterada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocoes_alteradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Escaninho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Código do escaninho deve conter apenas números', regex='^\\d+$')])),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escaninhos', to='estoque.produto')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escaninhos', to='estoque.setor')),
            ],
            options={
                'verbose_name': 'Escaninho',
                'verbose_name_plural': 'Escaninhos',
                'ordering': ['setor__nome', 'codigo'],
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['codigo_barras'], name='estoque_pro_codigo__986ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['em_promocao'], name='estoque_pro_em_prom_52d777_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['data_cadastro'], name='estoque_pro_data_ca_55fce0_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['valor_venda'], name='estoque_pro_valor_v_6f5df5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='escaninho',
            unique_together={('setor', 'codigo')},
        ),
    ]
