# Generated by Django 5.2.7 on 2025-10-31 01:21

import producao.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', producao.models.UserManager()),
            ],
        ),
    ]
