# Generated by Django 5.2.7 on 2025-11-07 01:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0004_alter_user_is_superuser_statusdashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 7, 1, 23, 28, 395047, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lote',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.product'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
