# Generated by Django 5.2.5 on 2025-10-28 23:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='machines/')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('registro', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_contratacao', models.DateField()),
                ('cargo', models.CharField(choices=[('PRODUCAO', 'Produção'), ('LIDER_PRODUCAO', 'Líder de Produção'), ('INSPECAO', 'Inspeção'), ('MANUTENCAO', 'Manutenção'), ('ADMIN', 'Admin')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('data_inspecao', models.DateTimeField(blank=True, null=True)),
                ('status_inspecao', models.CharField(blank=True, choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], max_length=10, null=True)),
                ('inspetor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_inspecionados', to='monitoring.funcionario')),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes_executadas', to='monitoring.funcionario')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='monitoring.maquina')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ItemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='monitoring.lote')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_produzidos', to='monitoring.maquina')),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='monitoring.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='monitoring.produto'),
        ),
    ]
