# Generated by Django 5.2.5 on 2025-10-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
