# Generated by Django 5.2.7 on 2025-11-05 01:42

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='endereço de email')),
                ('nome', models.CharField(max_length=150, verbose_name='nome completo')),
                ('numero_registro', models.CharField(max_length=50, unique=True, verbose_name='número de registro')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'Formato inválido para CPF')], verbose_name='CPF')),
                ('data_contratacao', models.DateField(default=django.utils.timezone.now, verbose_name='data de contratação')),
                ('cargo', models.CharField(choices=[('PRODUCAO', 'Produção'), ('CHEFE_PRODUCAO', 'Chefe de Produção'), ('INSPECAO', 'Inspeção'), ('MANUTENCAO', 'Manutenção'), ('ADMIN', 'Admin')], default='PRODUCAO', max_length=20, verbose_name='cargo')),
                ('groups', models.ManyToManyField(blank=True, related_name='funcionarios_groups', to='auth.group', verbose_name='grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='funcionarios_permissions', to='auth.permission', verbose_name='permissões de usuário')),
            ],
            options={
                'verbose_name': 'funcionário',
                'verbose_name_plural': 'funcionários',
            },
        ),
    ]
