# Generated by Django 5.2.7 on 2025-11-05 23:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome da linha')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'linha de produção',
                'verbose_name_plural': 'linhas de produção',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=20, verbose_name='prioridade')),
                ('resolvido', models.BooleanField(default=False, verbose_name='resolvido')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='data de resolução')),
                ('observacoes_resolucao', models.TextField(blank=True, verbose_name='observações da resolução')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_criados', to=settings.AUTH_USER_MODEL)),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resolvidos', to=settings.AUTH_USER_MODEL)),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='producao.linha')),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva')], max_length=20, verbose_name='tipo de manutenção')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('data_agendada', models.DateTimeField(verbose_name='data agendada')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20, verbose_name='status')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='data de início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='data de conclusão')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('duracao_estimada', models.DurationField(verbose_name='duração estimada')),
                ('custo_estimado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='custo estimado')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='producao.linha')),
                ('responsavel', models.ForeignKey(limit_choices_to={'cargo': 'MANUTENCAO'}, on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'manutenção',
                'verbose_name_plural': 'manutenções',
                'ordering': ['data_agendada'],
            },
        ),
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='número da ordem')),
                ('produto', models.CharField(max_length=200, verbose_name='produto')),
                ('quantidade_planejada', models.PositiveIntegerField(verbose_name='quantidade planejada')),
                ('quantidade_produzida', models.PositiveIntegerField(default=0, verbose_name='quantidade produzida')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='data de início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='data de conclusão')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PRODUCAO', 'Em Produção'), ('PAUSADA', 'Pausada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='producao.linha')),
                ('responsavel', models.ForeignKey(limit_choices_to={'cargo': 'CHEFE_PRODUCAO'}, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ordem de produção',
                'verbose_name_plural': 'ordens de produção',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRODUCAO', 'Produção'), ('PARADA', 'Parada'), ('MANUTENCAO', 'Manutenção'), ('INSPECAO', 'Inspeção')], max_length=20, verbose_name='tipo de registro')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='data e hora')),
                ('quantidade', models.PositiveIntegerField(default=0, verbose_name='quantidade')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to=settings.AUTH_USER_MODEL)),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='producao.ordemproducao')),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
                'ordering': ['-data_hora'],
            },
        ),
    ]
