# Generated by Django 5.2.7 on 2025-11-05 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_linha_alerta_manutencao_ordemproducao_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve conter exatamente 11 dígitos numéricos')], verbose_name='CPF'),
        ),
    ]
