# Generated by Django 5.2.7 on 2025-11-05 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(help_text='Digite apenas os 11 números do CPF, sem pontos ou traços', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve conter exatamente 11 dígitos numéricos')], verbose_name='CPF'),
        ),
    ]
