# Generated by Django 5.2.7 on 2025-11-07 01:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0004_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='código identificador')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='maquinas/', verbose_name='foto')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
            ],
            options={
                'verbose_name': 'máquina',
                'verbose_name_plural': 'máquinas',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='código do lote')),
                ('data_hora_inicio', models.DateTimeField(blank=True, null=True, verbose_name='data e hora de início')),
                ('data_hora_final', models.DateTimeField(blank=True, null=True, verbose_name='data e hora de finalização')),
                ('data_inspecao', models.DateTimeField(blank=True, null=True, verbose_name='data de inspeção')),
                ('status_inspecao', models.CharField(blank=True, choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], max_length=20, null=True, verbose_name='status da inspeção')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='lotes_qrcodes/', verbose_name='QR Code')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('responsavel_inspecao', models.ForeignKey(blank=True, limit_choices_to={'cargo': 'INSPECAO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspecoes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='producao.produto')),
            ],
            options={
                'verbose_name': 'lote',
                'verbose_name_plural': 'lotes',
                'ordering': ['-data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ManutencaoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data/hora da manutenção')),
                ('descricao', models.TextField(verbose_name='descrição da manutenção')),
                ('responsavel', models.ForeignKey(limit_choices_to={'cargo': 'MANUTENCAO'}, on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='producao.maquina')),
            ],
            options={
                'verbose_name': 'manutenção de máquina',
                'verbose_name_plural': 'manutenções de máquina',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ItemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data e hora do item')),
                ('identificador', models.CharField(blank=True, max_length=200, verbose_name='identificação do item')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='producao.lote')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_produzidos', to='producao.maquina')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='producao.produto')),
            ],
            options={
                'verbose_name': 'item de produção',
                'verbose_name_plural': 'itens de produção',
                'ordering': ['-data_hora'],
            },
        ),
    ]
