# Generated by Django 5.2.5 on 2025-11-07 01:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0)),
                ('foto', models.TextField(default='sem foto')),
                ('nome', models.CharField(default='Máquina sem nome', max_length=250)),
                ('descricao', models.CharField(max_length=250)),
                ('categoria', models.CharField(choices=[('CORTE', 'Máquina de Corte'), ('MONTAGEM', 'Máquina de Montagem'), ('INSPECAO', 'Máquina de Inspeção'), ('EMBALAGEM', 'Máquina de Embalagem'), ('MANUTENCAO', 'Máquina de Manutenção')], default='CONVENCIONAL', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Produto sem nome', max_length=300)),
                ('codigo', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=300)),
                ('categoria', models.CharField(choices=[('PRODUCTION', 'Máquina de Produção'), ('AUTOMATED_MACHINE', 'Máquina Automatizada'), ('MAINTENANCE_MACHINE', 'Máquina de Manutenção')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=12, unique=True)),
                ('numero_registro', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('data_contratacao', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(choices=[('PRODUCAO', 'Produção'), ('CHEFE_PRODUCAO', 'Chefe de Produção'), ('INSPECAO', 'Inspeção'), ('MANUTENCAO', 'Manutenção'), ('ADMIN', 'Admin')], default='PRODUCAO', max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_final', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_inspecao', models.DateTimeField(default=django.utils.timezone.now)),
                ('qr_code', models.TextField()),
                ('status', models.CharField(choices=[('APPROVED', 'Aprovado'), ('REPROVED', 'Reprovado')], default='APPROVED', max_length=100)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='app.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='ItensLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.lote')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.maquina')),
            ],
        ),
    ]
