# Generated by Django 5.2.7 on 2025-11-11 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='code',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='Reprovado',
        ),
        migrations.AddField(
            model_name='lote',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('Producao', 'producao'), ('Lider_producao', 'lider de producao'), ('Inspecao', 'inspecao'), ('Engenharia', 'engenharia'), ('Tecnico', 'tecnico'), ('Manutencao', 'manutencao'), ('Admin', 'admin')], max_length=50),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dt_contratacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lote',
            name='dthFim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e hora de fim'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='dthInicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='app.categoria'),
        ),
        migrations.DeleteModel(
            name='Producao',
        ),
    ]
