# Generated by Django 5.2.7 on 2025-11-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categoria_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='status',
            new_name='status_inspecao',
        ),
    ]
