# Generated by Django 5.2.7 on 2025-10-30 22:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_contratacao', models.DateField()),
                ('cargo', models.CharField(choices=[('MOTORISTA', 'Motorista'), ('MECANICO', 'Mecânico'), ('SUPERVISOR_FROTA', 'Supervisor de Frota'), ('ENGENHEIRO', 'Engenheiro'), ('ADMIN', 'Admin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('CARRO', 'Carro'), ('VAN', 'Van'), ('CAMINHAO', 'Caminhão')], max_length=10)),
                ('data_aquisicao', models.DateField()),
                ('data_ultima_manutencao', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva')], max_length=10)),
                ('descricao', models.TextField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tecnico', models.ForeignKey(limit_choices_to={'cargo': 'MECANICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes_tecnico', to='frota.funcionario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='frota.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_termino', models.DateTimeField(blank=True, null=True)),
                ('destino', models.CharField(max_length=100)),
                ('quilometragem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motorista', models.ForeignKey(limit_choices_to={'cargo': 'MOTORISTA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens_motorista', to='frota.funcionario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='frota.veiculo')),
            ],
        ),
    ]
