# Generated by Django 5.2.7 on 2025-10-30 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('nacionalidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Acomodacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('standard', 'Standard'), ('suite', 'Suíte'), ('master', 'Master')], max_length=20)),
                ('capacidade_maxima', models.PositiveIntegerField()),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupada', 'Ocupada'), ('manutencao', 'Em manutenção')], default='disponivel', max_length=20)),
                ('data_ultima_limpeza', models.DateField(blank=True, null=True)),
                ('funcionario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limpezas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='hotel.acomodacao')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hotel.acomodacao')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='hotel.hospede')),
            ],
        ),
    ]
