# Generated by Django 5.2.6 on 2025-09-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('nome_titular', models.CharField(max_length=100)),
                ('validade', models.CharField(max_length=5)),
                ('codigo', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EM_PROCESSAMENTO', 'Em processamento'), ('PAGAMENTO_APROVADO', 'Pagamento aprovado'), ('NOTA_FISCAL_EMITIDA', 'Nota fiscal emitida'), ('EM_PREPARACAO', 'Em preparação'), ('ENVIADO', 'Enviado'), ('RECEBIDO', 'Recebido'), ('PAGAMENTO_REPROVADO', 'Pagamento reprovado'), ('CANCELADO', 'Cancelado'), ('SOLICITACAO_DEVOLUCAO', 'Solicitação de devolução'), ('EM_DEVOLUCAO', 'Em devolução'), ('DEVOLVIDO', 'Devolvido'), ('DEVOLUCAO_CANCELADA', 'Devolução cancelada')], default='EM_PROCESSAMENTO', max_length=30)),
                ('metodo_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartão de crédito')], max_length=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('codigo_rastreamento', models.CharField(blank=True, max_length=50, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
