# Generated by Django 5.2.5 on 2025-09-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_accounttoken_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttoken',
            name='balance',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
