# Generated by Django 5.2.5 on 2025-08-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('TERROR', 'TERROR'), ('FICÇÃO', 'FICÇÃO'), ('COMÉDIA', 'COMÉDIA'), ('DOCUMENTÁRIO', 'DOCUMENTÁRIO'), ('AÇÃO', 'AÇÃO'), ('SUSPENSE', 'SUSPENSE')], max_length=50)),
                ('published_date', models.DateField()),
                ('photo', models.CharField(max_length=1000)),
                ('classification', models.IntegerField()),
                ('directors', models.ManyToManyField(to='app.directors')),
            ],
        ),
    ]
