# Generated by Django 5.2.6 on 2025-10-29 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nif', models.CharField(max_length=15, unique=True)),
                ('hired_at', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=15, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('inspection_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REPROVED', 'Reproved')], default=None, max_length=50)),
                ('inspector_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Lot_inspector_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=150)),
                ('lot_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Item_lot_FK', to='app.lot')),
                ('machine_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Item_machine_FK', to='app.machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('machine_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MachineMaintenance_machine_FK', to='app.machine')),
                ('user_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MachineMaintenance_user_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('category_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_category_FK', to='app.category')),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='product_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Lot_product_FK', to='app.product'),
        ),
    ]
