# Generated by Django 5.2.7 on 2025-10-29 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('numero_registro', models.CharField(max_length=50, unique=True)),
                ('data_contratacao', models.DateField(null=True)),
                ('cargo', models.CharField(choices=[('PRODUCAO', 'Produção'), ('LIDER_PRODUCAO', 'Líder de Produção'), ('INSPECAO', 'Inspeção'), ('ENGENHARIA', 'Engenharia'), ('MANUTENCAO', 'Manutenção'), ('ADMIN', 'Administração')], default='PRODUCAO', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('data_inspecao', models.DateTimeField(blank=True, null=True)),
                ('status_inspecao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='PENDENTE', max_length=10)),
                ('responsavel_inspecao', models.ForeignKey(limit_choices_to={'cargo': 'INSPECAO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_inspecionados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_identificador', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ultima_data_manutencao', models.DateTimeField()),
                ('responsavel_manutencao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas_mantidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_manutencao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('responsavel', models.ForeignKey(limit_choices_to=models.Q(('cargo', 'MANUTENCAO'), ('cargo', 'ENGENHARIA'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_manutencao', to='app.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_item', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_produzidos', to='app.lote')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.maquina')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.produto')),
            ],
        ),
    ]
