# Generated by Django 5.2.7 on 2025-10-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('PRODUCAO', 'Producao'), ('LIDER_PRODUCAO', 'Líder de Producao'), ('INSPECAO', 'Inspecao'), ('ENGENHARIA', 'Engenharia'), ('MANUTENCAO', 'Manutencao'), ('ADMIN', 'Administracao')], default='PRODUCAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='ultima_data_manutencao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
