# Generated by Django 5.2.5 on 2025-08-15 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_director_movie_directors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FavoriteMovie_movie_FK', to='app.movie')),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FavoriteMovie_user_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('plan_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserPlan_plan_FK', to='app.plan')),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserPlan_user_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
